### ISSUE TITLE
Endpoint 'graphql' not found?

### ISSUE THREAD

**Issue by obaid** [mll-lab/laravel-graphql-playground#1]
I am trying to give this a go but when I try to run it by going to: `http://localhost/graphql-playground` I get a network 404 for `http://localhost/graphql` and I think that the endpoint route is not registering properly. 

Am i missing something?

**Comment by spawnia** [comment]
Do you have a running endpoint at `/graphql`? This package only adds a route for the Playground UI, it does not come with a backend.

**Comment by hailwood** [comment]
@spawnia #2 should help this.

**Comment by spawnia** [comment]
@obaid I am going to close this issue for now, feel free to reopen if you are still experience issues.

**Comment by obaid** [comment]
Thanks @hailwood for the link. That did solve the problem for me.
