### ISSUE TITLE
Lumen Support

### ISSUE THREAD

**Issue by axe-me** [mll-lab/laravel-graphql-playground#13]
Please add Lumen support :)

**Comment by spawnia** [comment]
I will happily take a PR on this.

**Comment by tsandrini** [comment]
I'd appreciate this as well since this technology goes hand in hand with lumen (targeting to be a lightweight API), so I'd naturally expect its appropriate support.

**Comment by spawnia** [comment]
Support is added in the `v2.0.0` release: https://github.com/mll-lab/laravel-graphql-playground/releases/tag/v2.0.0

**Comment by tsandrini** [comment]
@spawnia I had to manually setup `app()->configPath()` (which is not in Lumen by default), but apart from that it works like charm, thank you. :)

**Comment by spawnia** [comment]
> @spawnia I had to manually setup `app()->configPath()` (which is not in Lumen by default), but apart from that it works like charm, thank you. :)

Fixed as of https://github.com/mll-lab/laravel-graphql-playground/releases/tag/v2.0.1
