### ISSUE TITLE
How to pass headers ?

### ISSUE THREAD

**Issue by sadhakbj** [mll-lab/laravel-graphql-playground#15]
For the protected / guarded routes I need to pass the JWT token , how can I do this with Larvel graphql playground ?

**Comment by mfn** [comment]
You configured a Laravel Middleware for it and tell graph-playground to use it via https://github.com/mll-lab/laravel-graphql-playground/blob/dd014d8edfe7b845a22e1612b935f6055e99c960/config/graphql-playground.php#L9-L12

**Comment by sadhakbj** [comment]
This is not the solution that I need, this config will basically prevent me from viewing the playground. 

I am using Laravel passport  for JWT authentication.
Inside my schema.graphql i have the following query:
```
 categories: [Category] @all @middleware(checks: ["auth:api"])
```

I want to get access to this query in the same that we used to do for the restful APIS by passing the JWT token (probably from the playground for testing) .

The query in my playground to get the categories looks like:
```
query {
  categories {
  name
}
}
```

When I press the run button I get the following error: 
```
"errors": [
    {
      "debugMessage": "Route [login] not defined.",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "categories"
      ],
```

I want to implement the authentication using Laravel Lighthouse and playground.

**Comment by spawnia** [comment]
Alright. It seems that this issue does not really concern this repo though, since it seems to be a more general problem with authentication. This is really only a thin integration layer for GraphQL Playground.

**Comment by josevalero** [comment]
![imagen](https://user-images.githubusercontent.com/43073863/105439182-fc39e800-5c29-11eb-954e-5e8559fa32f7.png)


@sadhakbj maybe that answer your question !!

**Comment by sadhakbj** [comment]
@josevalero yes the issue was solved long back
