### ISSUE TITLE
[Feature Request] Update to latest graphql-playground version

### ISSUE THREAD

**Issue by robsontenorio** [mll-lab/laravel-graphql-playground#16]
It would be nice to update it to the latest graphql-playground version.

https://github.com/prisma/graphql-playground/releases

**Comment by spawnia** [comment]
I think the links we are using just point to the latest version anyways?

**Comment by spawnia** [comment]
@robsontenorio in my opinion, the way this project is set up already makes it so it defaults to the latest version. Correct me if i am wrong.
