### ISSUE TITLE
How to change subscription end point?

### ISSUE THREAD

**Issue by jagadeshanh** [mll-lab/laravel-graphql-playground#23]
I wanted to change subscription endpoint of graphql-playground. Anyone has any idea?

I tried

`    'extensions' => [
        'endpoints' => [
            'dev' => [
                'subscription' => [
                    'url' => 'wss://someendpoint',
                ]
            ]
        ]
    ]`

**Comment by spawnia** [comment]
Is that a seperate endpoint?

**Comment by jagadeshanh** [comment]
@spawnia yes its a separate endpoint

**Comment by spawnia** [comment]
Can you link to a relevant section of the `graphql-playground` docs?

**Comment by jagadeshanh** [comment]
I tried to follow this tutorial and assumed there might be some sort of configurations

[https://github.com/prisma/graphql-config#specifying-endpoint-info](url)

**Comment by spawnia** [comment]
https://github.com/prisma/graphql-playground#properties seems more like what we need.

Let's find a flexible but still simple enough approach of exposing config options via `graphql-playground.php`

**Comment by spawnia** [comment]
You can change any settings in the published view: https://github.com/mll-lab/laravel-graphql-playground#usage
