### ISSUE TITLE
Route::group call is incorrect for Laravel 5.8

### ISSUE THREAD

**Issue by nathanburgess** [mll-lab/laravel-graphql-playground#24]
`Shared attributes are specified in an array format as the first parameter to the Route::group method.`
https://laravel.com/docs/5.8/routing#route-groups

If the first argument to `Route::group` isn't a function, it must be an array.

This can be resolved by changing 
https://github.com/mll-lab/laravel-graphql-playground/blob/8ce87760a5991ba4c9b9d5924f0b0a2811535fc6/src/GraphQLPlaygroundServiceProvider.php#L36
to `[config('graphql-playground.route')],`

**Comment by tabirkeland** [comment]
Same issue, had to remove this repo until it has been resolved.

**Comment by nathanburgess** [comment]
@tabirkeland Yep, I just forked it and made the change there. Hoping that someone will update this repo so can drop the fork.

**Comment by spawnia** [comment]
@nathanburgess that someone could be you. Can you provide a Pull Request?

**Comment by janicerar** [comment]
I had the same issue. 

This is because 'route' was renamed to 'route_name'. 

In this pull request:
https://github.com/mll-lab/laravel-graphql-playground/commit/b07606b350c4f61182220394e9c5109a08c3bac3

Just rename config variable and you should be fine.

**Comment by spawnia** [comment]
@janicerar good find, totally forgot about that.

So yeah, that was a breaking change in the `v1.0.0` release. Updated the release description to clarify the config change.

https://github.com/mll-lab/laravel-graphql-playground/releases/tag/v1.0.0
