### ISSUE TITLE
Add config for session authentication

### ISSUE THREAD

**Issue by olivernybroe** [mll-lab/laravel-graphql-playground#26]
In our system we are using graphql through sessions, but to get it to work with graphql playground we had to change stuff in the view file and research what the GraphQLPlayground parameters was called.
In our application we also have CSRF protection on, so we also had to add a custom header to the request.
We fixed this by adding `<meta name="csrf-token" content="{{ csrf_token() }}">` in the header and changing the `init` parameters to the following
```
GraphQLPlayground.init(root, {
        endpoint: "{{url(config('graphql-playground.endpoint'))}}",
        settings: {
            'request.credentials': 'same-origin',
        },
        headers: {
            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content
        }
    })
```

What I am proposing is adding two config parameters, one to set the `request.credentials` and one to enable CSRF token passthrough.

**Comment by spawnia** [comment]
Is there any reason not to enable CSRF? We might just add it in statically.

Not too sure about the `request.credentials`, why is that needed?

**Comment by olivernybroe** [comment]
Well In cases where you don't use CSRF, I think it might fail when trying to generate the token? Not really sure about it as I always use CSRF.

The `request.credentials` with `same-origin` defines if it should pass the headers from the current request to all request it makes to graphql. This is needed to pass the cookies header with session id to all request to graphql

**Comment by spawnia** [comment]
Looks like Laravel includes it by default, so i think we should do the same. It can be removed from the published view file if it is not wanted. Can you send a PR?

I enhanced the README with some info about how to add arbitrary settings. I don't want to duplicate all the settings in the config file, as it would be hard to maintain.

**Comment by olivernybroe** [comment]
@spawnia Ah sure, let's do that then. 
I'll first be able to make a PR in a couple of days, else I don't mind that you do it :)

**Comment by spawnia** [comment]
@olivernybroe nah i am good 😉

**Comment by JasonTheAdams** [comment]
@olivernybroe Any progress on this? We would also benefit from being able to authenticate via session, and I'm not sure I have as strong a grasp as you do as to what's necessary.

**Comment by JasonTheAdams** [comment]
For some reason `csrf_token()` is returning empty/null so the meta content is empty. The token is working everywhere outside of GraphQL Playground. Did I miss something in your steps?

**Comment by olivernybroe** [comment]
@JasonTheAdams yeah sorry, I really haven't had time and forgot all about this. 
If anybody else wants to then please create the pr :) 

Hmm sounds wierd, did you change the init config?

**Comment by JasonTheAdams** [comment]
@olivernybroe Yeah, I changed the init config. The token is displaying by this point, but I found that this package view triggers a different session than the one otherwise used for the other pages. Pretty strange.

**Comment by spawnia** [comment]
Open for PR's.

**Comment by JasonTheAdams** [comment]
@spawnia If I can figure out how to get it to use the same session then I'll definitely look to submit a PR. If you can give me a lead of any kind I would appreciate it. I'm not sure how Laravel determines which session to use during a request.

**Comment by JasonTheAdams** [comment]
So I actually about to make a PR for this. Then I realized that the view can be published and overwritten with exactly these details. Seems like that may be an adequate solution?

**Comment by Empereol** [comment]
> So I was actually about to make a PR for this. Then I realized that the view can be published and overwritten with exactly these details. Seems like that may be an adequate solution?

@JasonTheAdams , could you expand on this? I have published the graphql-playground view but still cannot get any query with `@auth` to work correctly.
