### ISSUE TITLE
Laravel 5.8 Support - Problem with Route

### ISSUE THREAD

**Issue by michaelrondon27** [mll-lab/laravel-graphql-playground#31]
In Laravel 5.8 the route::group() is accepting the first parameter as an array. Not receiving said array fails in the GraphQLPlaygroundServiceProvider, exactly where is the route: group()

I soucione passing the variable as an array, as you can see in the code below

`Route::group(
            [config('graphql-playground.route')],
            function (): void {
                Route::get(
                    config('graphql-playground.route_name', 'graphql-playground'),
                    GraphQLPlaygroundController::class.'@get'
                )->name('graphql-playground');
            }
        );`

**Comment by spawnia** [comment]
Is this actually still an issue?

**Comment by michaelrondon27** [comment]
Hi, i'm from venezuela and now i'm working in spain. I apologize in advance
because my English is not very good.

The question is that my boss told me to upgrade laravel 5.7 to 5.8, your
package works pretty well with 5.7

The problem is that in version 5.8, for the route:group () they put first
parameter into an array. This in version 1.10 that you have to that route
is passed a string and this leads to an error with the route. I put the
first parameter of the route in square brackets and it works fine.

**Comment by spawnia** [comment]
You should upgrade your configuration, see https://github.com/mll-lab/laravel-graphql-playground/blob/master/config/graphql-playground.php
