### ISSUE TITLE
Include table name on where directive

### ISSUE THREAD

**Issue by colighto** [mll-lab/laravel-graphql-playground#36]
Hello, on your where directive is there a way I can specify the table where an attribute is coming from. Just like the original model call of where something like:

$model->where('products.name', 'product name');

I have been attempting something like:

@where(products.name:  String, operator: LIKE)

But it would end up in a syntax error

**Comment by spawnia** [comment]
I think this question is meant for Lighthouse.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)
