### ISSUE TITLE
JavaScript Error when clicking "copy curl"

### ISSUE THREAD

**Issue by mazedlx** [mll-lab/laravel-graphql-playground#38]
When I click on `copy curl` i receive the following JS error:

```js
Uncaught TypeError: can't access property "getState", t.context.store is undefined in TopBar.tsx:115:20
```

Everything else is working as expected.
I am using version 2.1.0. Any thoughts on this?

**Comment by spawnia** [comment]
Seems like an issue with upstream, i don't think there is anything we can do here. Try https://github.com/prisma-labs/graphql-playground.

If there is something we can do, feel free to reopen.

**Comment by mazedlx** [comment]
@spawnia my bad, there's already an issue there, I'll leave it here for reference https://github.com/prisma-labs/graphql-playground/issues/1219
