### ISSUE TITLE
Suggestion: consider a debug tab

### ISSUE THREAD

**Issue by Jofairden** [mll-lab/laravel-graphql-playground#39]
In short I had this issue where my schema was corrupted
The only way I was able to identify the root causes of the issue was by opening my browser console and toggling the docs panel.
I think you should consider a tab that can show the errors that I got by using the above method. It would be very useful during development.

**Comment by spawnia** [comment]
This package is only a thin integration layer for https://github.com/prisma-labs/graphql-playground. This seems like it can be implemented or fixed upstream.

**Comment by Jofairden** [comment]
Alright, I left an issue there.
