### ISSUE TITLE
Publish package under different tag name

### ISSUE THREAD

**Issue by ssi-anik** [mll-lab/laravel-graphql-playground#40]
I wanted to publish the configuration for `nuwave/lighthouse`. I had no intention to publish your configuration. But as I had to select the option, it published your configuration too. So, I'd think that it'd be great to publish your content under a different tag. Maybe `gql.playground` or simply `playground`. 
![Screen Shot 2020-07-17 at 2 12 26 PM](https://user-images.githubusercontent.com/2676602/87764820-c9f19d00-c838-11ea-9ac3-a0bf415454e3.png)
I wanted to publish `lighthouse`'s configuration and came up with publishing your configuration too.
Thanks BTW.

**Comment by spawnia** [comment]
Thanks, namespacing the tags makes total sense.
