### ISSUE TITLE
Not support for laravel 8 

### ISSUE THREAD

**Issue by caizhigang97** [mll-lab/laravel-graphql-playground#44]
Laravel 8.0 just released, any idea when this package will support it?
![image](https://user-images.githubusercontent.com/21142662/92562105-03c6a900-f2a8-11ea-9c3f-8a02acd7e25f.png)
Thanks~

**Comment by caizhigang97** [comment]
#43

**Comment by spawnia** [comment]
> Would you take care of this right away, please?

You might want to watch how you phrase such questions, this one came of very demanding. I am sure you mean well, but I don't like the tone of this.

**Comment by spawnia** [comment]
Laravel 8 is supported as of https://github.com/mll-lab/laravel-graphql-playground/releases/tag/v2.4.0

**Comment by caizhigang97** [comment]
Sorry,I'm not good at English. Thank you~
