### ISSUE TITLE
Method signature issues in GraphQLPlaygroundServiceProvider#loadRoutesFrom

### ISSUE THREAD

**Issue by voydz** [mll-lab/laravel-graphql-playground#45]
Hi,

due to changes in the ServiceProvider signature (https://github.com/laravel/framework/pull/34866) this package fails to load its service provider.

Pull request incoming.

best regards

**Comment by voydz** [comment]
It seems the change was reverted in https://github.com/laravel/framework/commit/7fff6ea5e0a3b4e604be7531f7ab64d5436128ba.

**Comment by spawnia** [comment]
Thanks @voydz for taking care of this.
