### ISSUE TITLE
Add functionality to provide the subscription endpoint.

### ISSUE THREAD

**Issue by ssi-anik** [mll-lab/laravel-graphql-playground#47]
Graphql playground supports providing the [subscription url](https://github.com/graphql/graphql-playground#properties). 
Please update this package like it's done for the endpoint.

https://github.com/mll-lab/laravel-graphql-playground/blob/b14caee7de995deeb60b2bd6f602fdd1020eccb7/views/index.blade.php#L26-L28

**Comment by spawnia** [comment]
That should be pretty easy to implement, do you care enough to add a PR?

**Comment by ssi-anik** [comment]
Okay. will send a PR by today

**Comment by spawnia** [comment]
Released in https://github.com/mll-lab/laravel-graphql-playground/releases/tag/v2.5.0
