### ISSUE TITLE
Update headers

### ISSUE THREAD

**Issue by roosht3** [mll-lab/laravel-graphql-playground#50]
Each time the csrf token is changed the old tabs needs to be updated with the latest `X-CSRF-TOKEN` value. Is there a way that can called to update all the opened tabs's header values

**Comment by spawnia** [comment]
I don't think there is any need for that, the CSRF token generated when intially loading the GraphQL playground should work fine. Follow https://github.com/mll-lab/laravel-graphql-playground#configure-session-authentication

**Comment by roosht3** [comment]
@spawnia In my case it is really required. I am using the above said method and it is working fine. There are lot of old tabs and once I restart the docker or some other manual manipulation of testing invalidates the old csrf tokens. Once I go into playground again there is a new tab initialized with the new csrf token. In this case, I have to update each and every tab with the new csrf token

**Comment by spawnia** [comment]
If you figure out a way to do this, feel free to contribute.
