### ISSUE TITLE
Exclude mutation from playground

### ISSUE THREAD

**Issue by pitylee** [mll-lab/laravel-graphql-playground#51]
I am trying to hide a mutation from the playground.

So what I tried so far, is I took the file `./resources/views/vendor/graphql-playground/index.blade.php` and modified the settings object:

So what I tried so far, is I took the file `./resources/views/vendor/graphql-playground/index.blade.php` and modified the settings object:
```
        GraphQLPlayground.init(root, {
            endpoint: "{{url(config('graphql-playground.endpoint'))}}",
            config: {
                schema: {
                    mutation: {
                        exclude: ['mutationName', '_mutationNamePayload']
                    }
                },
                extensions: {
                    endpoints: {
                        production: {
                            url: "{{url(config('graphql-playground.endpoint'))}}",
                            exclude: ['mutationName', '_mutationNamePayload'],
                            mutations: {
                                exclude: ['mutationName', '_mutationNamePayload']
                            }
                        }
                    }
                },
                mutation: {
                    exclude: ['mutationName']
                }
            },
            headers: {
               'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content
            }
        })
```

No luck so far, I can find no information on how to exclude specific parts, and the only similiar issue found is this:
https://community.neo4j.com/t/how-do-i-exclude-auto-generated-mutations/17767

**Comment by spawnia** [comment]
This package is only a thin integration layer for https://github.com/prisma-labs/graphql-playground. This seems like it can be implemented or fixed upstream.
