### ISSUE TITLE
Couldn`t open schema and docs tabs on production server (infinitely loading content)

### ISSUE THREAD

**Issue by studiowizjo** [mll-lab/laravel-graphql-playground#57]
Playground works perfectly fine on localhost, but on production where I try to open dosc or schema tab it shows spinner loading icon infinitely.

I can do successfully queries.

Noticed problems and differences between localhost: 

1. Console shows error in file **Playground.tsx:313**:  
```
ServerError: Server response was missing for query 'IntrospectionQuery'.
    at c (bundle.esm.js:22:17)
    at bundle.esm.js:52:13
```

2. In the bar just after "History button" shows message: `Server cannot be reached`

**Comment by spawnia** [comment]
Probably has the wrong URL, often it is missing `https`.

**Comment by studiowizjo** [comment]
I didn`t typed anything to this field and it is also not prefilled with anything.

The file you pointed wasn`t also altered by me and by default header was set there to:

```php
protected $headers = Request::HEADER_X_FORWARDED_ALL;
```

I tried to change it as you suggested, but it didnt help.

It is something with configuration, but it is really hard for me to debug this, because error points to React file and I am not familiar with it and also this can be some intern package things, which could require longer analysis of package way of action. 

I would be very grateful to pointing me any idea where I could search  to find out problem.

You can preview issue here: https://dev.rogalik-panel.pl/graphql-playground

**Comment by spawnia** [comment]
![image](https://user-images.githubusercontent.com/12158000/177558320-d026a862-c20a-4e68-99be-a9bf47c6eb4b.png)

**Comment by studiowizjo** [comment]
Thank you very much. Problem solved :)
