### ISSUE TITLE
Issue with download-assets in Windows

### ISSUE THREAD

**Issue by basudebpal** [mll-lab/laravel-graphql-playground#9]
Hi,
Thank you for the open source project. I appreciate your hard work.
I am developing on a Windows OS (7). I am facing an issue with "php artisan graphql-playground:download-assets" command. The problem, in my opinion, is the windows folder structure, which is causing this error while recursively creating the directory structure. Any solution to this problem is greatly appreciated. I, as of now, have manually created the necessary folders and pasted the necessary files.
Thanks in advance.
Full Stack trace below --

λ php artisan graphql-playground:download-assets -v

   ErrorException  : mkdir(): No such file or directory

  at E:\Web\PHP\laravel-demo\vendor\mll-lab\laravel-graphql-playground\src\DownloadAssetsCommand.php:49
  ```
  45|         $file = array_pop($parts);
    46|         $path = '';
    47|         foreach ($parts as $part) {
    48|             if (!is_dir($path .= "/$part")) {
  > 49|                 mkdir($path);
    50|             }
    51|         }
    52|         file_put_contents("$path/$file", $contents);
    53|     }
```

  Exception trace:

  1   mkdir("/E:\Web\PHP\laravel-demo\public\vendor")
      E:\Web\PHP\laravel-demo\vendor\mll-lab\laravel-graphql-playground\src\DownloadAssetsCommand.php:49

  2   MLL\GraphQLPlayground\DownloadAssetsCommand::fileForceContents("/E:\Web\PHP\laravel-demo\public\vendor", "body{margin:0;padding:0;font-family:sans-serif;overflow:hidden}#root{height:100%}body{font-family:Open Sans,sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;color:rgba(0,0,0,.8);line-height:1.5;height:100vh;letter-spacing:.53px;margin-right:-1px!important}a,body,code,h1,h2,h3,h4,html,p,pre,ul{margin:0;padding:0;color:inherit}a:active,a:focus,button:focus,input:focus{outline:none}button,input,submit{border:none}button,input,pre{font-family:Open Sans,sans-serif}code{font-family:Consolas,monospace}
/*# sourceMappingURL=index.css.map*/")
      E:\Web\PHP\laravel-demo\vendor\mll-lab\laravel-graphql-playground\src\DownloadAssetsCommand.php:30

  3   MLL\GraphQLPlayground\DownloadAssetsCommand::handle()
      E:\Web\PHP\laravel-demo\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:29

  4   call_user_func_array([])
      E:\Web\PHP\laravel-demo\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:29

  5   Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      E:\Web\PHP\laravel-demo\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:87

  6   Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      E:\Web\PHP\laravel-demo\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:31

  7   Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      E:\Web\PHP\laravel-demo\vendor\laravel\framework\src\Illuminate\Container\Container.php:564

  8   Illuminate\Container\Container::call()
      E:\Web\PHP\laravel-demo\vendor\laravel\framework\src\Illuminate\Console\Command.php:183

  9   Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      E:\Web\PHP\laravel-demo\vendor\symfony\console\Command\Command.php:251

  10  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      E:\Web\PHP\laravel-demo\vendor\laravel\framework\src\Illuminate\Console\Command.php:170

  11  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      E:\Web\PHP\laravel-demo\vendor\symfony\console\Application.php:886

  12  Symfony\Component\Console\Application::doRunCommand(Object(MLL\GraphQLPlayground\DownloadAssetsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      E:\Web\PHP\laravel-demo\vendor\symfony\console\Application.php:262

  13  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      E:\Web\PHP\laravel-demo\vendor\symfony\console\Application.php:145

  14  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      E:\Web\PHP\laravel-demo\vendor\laravel\framework\src\Illuminate\Console\Application.php:89

  15  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      E:\Web\PHP\laravel-demo\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:122

  16  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      E:\Web\PHP\laravel-demo\artisan:37

**Comment by spawnia** [comment]
Hey, can you try the version on branch `download-assets-windows` and see if it resolves your issue?

Thanks for the report!

**Comment by basudebpal** [comment]
hi,
Thanks for the quick response. I am still getting a different error. Pasting the error part only instead of the full stack trace for readability.
λ php artisan graphql-playground:download-assets -v

   ErrorException  : mkdir(): No such file or directory

  at E:\Web\PHP\laravel-windows-demo\vendor\mll-lab\laravel-graphql-playground\src\DownloadAssetsCommand.php:46
```
    42|         // Start at the root directory
    43|         $path = '';
    44|         foreach ($parts as $part) {
    45|             if (!is_dir($path .= DIRECTORY_SEPARATOR . $part)) {
  > 46|                 mkdir($path);
    47|             }
    48|         }
    49|
    50|         file_put_contents(
```

  Exception trace:

  1   mkdir("\E:")
      E:\Web\PHP\laravel-windows-demo\vendor\mll-lab\laravel-graphql-playground\src\DownloadAssetsCommand.php:46

**Comment by basudebpal** [comment]
I will try some debugging from my end and let you know. I am still an amateur, so, fingers crossed :smile:

**Comment by spawnia** [comment]
Can you please try again with the updated version?

**Comment by basudebpal** [comment]
Hi spawnia,
It is working from my end. I use Windows OS only. I can't confirm if it works in Linux\unix env.
Thank you for your quick response. I am closing this issue now. :smile:
